name: "cd"

on:
  push:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm install
    - name: Version Number Increment
    - run: npm version patch
    - name: Publish
      run: npm run deploy
      env:
        VSCE_PAT: ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}